2016-06-12 05:30:43,817 - [INFO] - from play in pool-4-thread-3 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2016-06-12 05:38:56,906 - [INFO] - from application in play-internal-execution-context-1 
Application started!

2016-06-12 05:38:58,741 - [DEBUG] - from application in play-internal-execution-context-1 
** Morphia datastore: ro

2016-06-12 05:38:58,742 - [INFO] - from application in play-internal-execution-context-1 
Connected to Database!

2016-06-12 05:38:59,098 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2016-06-12 06:15:24,155 - [ERROR] - from application in New I/O worker #5 


! @70chm2flc - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 06:17:02,921 - [ERROR] - from application in New I/O worker #5 


! @70chm861l - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: missing return statement]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 06:17:40,543 - [INFO] - from application in play-internal-execution-context-1 
Application started!

2016-06-12 06:17:41,224 - [DEBUG] - from application in play-internal-execution-context-1 
** Morphia datastore: ro

2016-06-12 06:17:41,225 - [INFO] - from application in play-internal-execution-context-1 
Connected to Database!

2016-06-12 06:17:41,602 - [WARN] - from application in play-internal-execution-context-1 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:17:41,605 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2016-06-12 06:17:50,068 - [DEBUG] - from application in play-akka.actor.default-dispatcher-14 
Returned with URL: '/authenticate/google'

2016-06-12 06:17:50,445 - [DEBUG] - from application in play-akka.actor.default-dispatcher-14 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=4c383950-0173-4455-b766-fff0d39bc760

2016-06-12 06:17:55,242 - [DEBUG] - from application in play-akka.actor.default-dispatcher-11 
Returned with URL: '/authenticate/google?state=4c383950-0173-4455-b766-fff0d39bc760&code=4/omq2ySCBbq_gU7t14u9FEgAGLP4KiAeDULf97QcP_90'

2016-06-12 06:17:58,009 - [DEBUG] - from application in play-akka.actor.default-dispatcher-11 
{"access_token":"ya29.Ci__AhThSeONSAhLnDGjpC9N4cQBNXS-cXHRR-eqMpCffgYaI9e6S13T3yDtmPQpWw","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6InJjMFh1aFNDS0thNzY4R0hyRWd6Y2ciLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcwODY3OSwiZXhwIjoxNDY1NzEyMjc5fQ.REsl-QX4I4dElGWUzhMJWE-3G_6bP4h3s_sTDCV1ltImXyuEWqEWoT6rMMCvtD-bZEG4rfUciVCyh-w8zoYSeYVSIxRn1r9FkyBTDMCDGEgmmmC7180clD-IyBsmX-vlnsnn3XdVhZoKV_C0CscNqj7_4EXkewzXwbWdBlia6S9UbYntMRx-zZoLsNR1yIYmjMmW2jkFOD5K_v1Dm4FeAjskopfSEbQecgDDgXWMfvVGbcwDOSgyCu_pxlAsGjqsWNF8CY9qmhcZET9E-K5Kd2O-iG5mNaxHCk5_nmClyeBhWqg0qZ-Q-ADNg_nekL2OoJB3FWihRGcFtVZn45dwFw"}

2016-06-12 06:17:58,559 - [DEBUG] - from application in play-akka.actor.default-dispatcher-11 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 06:20:03,550 - [INFO] - from application in play-internal-execution-context-1 
Application started!

2016-06-12 06:20:04,211 - [DEBUG] - from application in play-internal-execution-context-1 
** Morphia datastore: ro

2016-06-12 06:20:04,211 - [INFO] - from application in play-internal-execution-context-1 
Connected to Database!

2016-06-12 06:20:04,341 - [WARN] - from application in play-internal-execution-context-1 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:20:04,343 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2016-06-12 06:20:14,477 - [DEBUG] - from application in play-akka.actor.default-dispatcher-20 
Returned with URL: '/authenticate/google'

2016-06-12 06:20:14,482 - [DEBUG] - from application in play-akka.actor.default-dispatcher-20 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=dcfbaeb1-8509-428d-93a4-77feeab036d7

2016-06-12 06:20:16,800 - [DEBUG] - from application in play-akka.actor.default-dispatcher-18 
Returned with URL: '/authenticate/google?state=dcfbaeb1-8509-428d-93a4-77feeab036d7&code=4/yGSFIHcGg3h_ckH8g5NMYMpV04YnjRMQg7oYUU30o7w'

2016-06-12 06:20:17,127 - [DEBUG] - from application in play-akka.actor.default-dispatcher-18 
{"access_token":"ya29.Ci__Ai2L2ORE6vTV3-R3pIVUGVtWFxDNBAGf7t-mHg4wL4H6NsypzrV6Hjb5Wd_pWQ","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6IjVORU1UZ1JaR2lEeGl3UHlrMmJjUUEiLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcwODgxOCwiZXhwIjoxNDY1NzEyNDE4fQ.PpcyNmvqdGTffk3saTvOXSns_XLY2Du6MpVyslPIrUhvZjRE1-DFTxdyuyoz-Sg4QvoqV69a9sxa10WUizKrT2BdLdunzkS_xPqOUejOfU-ewMvP81WshTE8cuLb6vBWelwuzUarP2gkddzBWmCxClqBbdNc48T_UsjnpbNiOi1z7QSMPOlD-7XMg9MByGS3nQE6CzNFmL_4Z0QTK1zs7P_xhUNfK0RwxhWGbc84k9NKQigzrYz2h-MbENvGtY4Q9X70efX8RJixBxaF4oDpr3BRZY6u-WSBkrPVQe7OcgRUY_pWiFXRslXgM-0BZd0br-2BV90s6hUPxtnCzGEaTg"}

2016-06-12 06:20:17,458 - [DEBUG] - from application in play-akka.actor.default-dispatcher-18 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 06:23:08,586 - [INFO] - from application in play-internal-execution-context-4 
Application started!

2016-06-12 06:23:09,242 - [DEBUG] - from application in play-internal-execution-context-4 
** Morphia datastore: ro

2016-06-12 06:23:09,244 - [INFO] - from application in play-internal-execution-context-4 
Connected to Database!

2016-06-12 06:23:09,377 - [WARN] - from application in play-internal-execution-context-4 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:23:09,380 - [INFO] - from play in play-internal-execution-context-4 
Application started (Dev)

2016-06-12 06:23:14,582 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
Returned with URL: '/authenticate/google'

2016-06-12 06:23:14,586 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=bfa32d4e-ee4c-4ce7-bf64-71bb710d8a81

2016-06-12 06:23:16,939 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
Returned with URL: '/authenticate/google?state=bfa32d4e-ee4c-4ce7-bf64-71bb710d8a81&code=4/wAOqgU1hvnm6sFcY9C6VYwtAEflWR8wWBb09znRHxBI'

2016-06-12 06:23:17,198 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
{"access_token":"ya29.Ci__Alsd6ug7uZ_2gXLOw9-bXULYDe4flJDXWe1H6QwOgLAu17aSUE-rfnpzSks-Fg","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6Ii0yTGZBcW5lV3luQ3d1UWhBaTQ1eXciLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcwODk5OCwiZXhwIjoxNDY1NzEyNTk4fQ.jZQQLnvAAvskdxpj4wTrdicvnHAxFSWWZNDIH34pOM4HfgPo9SK7K5_ZmguT5gRbRGkixP-Xvw0h3BL77Fp7kF9PVQuP4-9q2SOuCUQjTdUUNUBnBgLurWKqn0zBqCkLRIosFkd50AzhjDe7AIVQoiGKQ71Z_7vmglVY-RUx6WnuakINTMhgZenur9rEiOybYYh_XLpjn1T6r84VUp-SsMiGjGW1wcycfAPGhZu7uZw6W8T6l_3KE16KDuoQG0zoaGP_5vy9qprrMFZQjYt0VY0XoBC4RolOkMVWx87Tv5m8WzgaquWK5ofzaYLZae_95lQ26_T1uaDw5HSiUv5Jwg"}

2016-06-12 06:23:17,555 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 06:23:59,525 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
Returned with URL: '/authenticate/google'

2016-06-12 06:23:59,525 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=fa5fa579-d1c9-4d88-ba00-30a70171c95e

2016-06-12 06:24:01,919 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
Returned with URL: '/authenticate/google?state=fa5fa579-d1c9-4d88-ba00-30a70171c95e&code=4/_kVKQPwjqq5Db5iNIO6Abzcu-LIzuHa42WiqUDTVyoI'

2016-06-12 06:24:02,077 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
{"access_token":"ya29.Ci__ApcibTVpgwtC_ANLfW80FBdO4AZ5yBmnsTmdSY8mXjO1srKMmrFkE3gS-3-qoA","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6IkVBNUlkaGZaTlFFYWZsYWtsQ0p6emciLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcwOTA0MywiZXhwIjoxNDY1NzEyNjQzfQ.HwHzNmTsln0j2N83xviXf__OkXjhcrulS7OQcLqhS3CDjfUjH07K7ftdSNzUawZuapR025WojUZ4R-FMSErTsxCJjdSds_qxhgA0LH23hHNhmQRwJ-9HrkwmZplv6DqJ9hTPIbDESI4xHCIbNzbNBVsHjQ9hcwrYl5p4U9zruqMqXAEzw2cQ2YuBIAQz6MNYho2EdCi1MzCmVNlyhxl-9NNa-RaFj6hpb0Ntr2y2XkFEhI9TLN7MdpMUZivpVHW95GYjf13-PX5VVPtGvfKnle58sM9I9HmheEVruiTOAxyT3ETQ-jL3Mx-fPDGZeyVgow1iRIrZebB_61QsIftfjg"}

2016-06-12 06:24:02,303 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 06:42:02,594 - [INFO] - from application in play-internal-execution-context-6 
Application started!

2016-06-12 06:42:03,253 - [DEBUG] - from application in play-internal-execution-context-6 
** Morphia datastore: ro

2016-06-12 06:42:03,254 - [INFO] - from application in play-internal-execution-context-6 
Connected to Database!

2016-06-12 06:42:03,383 - [WARN] - from application in play-internal-execution-context-6 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:42:03,385 - [INFO] - from play in play-internal-execution-context-6 
Application started (Dev)

2016-06-12 06:42:44,637 - [DEBUG] - from application in play-akka.actor.default-dispatcher-46 
Returned with URL: '/authenticate/google'

2016-06-12 06:42:44,638 - [DEBUG] - from application in play-akka.actor.default-dispatcher-46 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=3d6c8db1-1db0-4d68-80a3-371ea4d5d235

2016-06-12 06:42:47,019 - [DEBUG] - from application in play-akka.actor.default-dispatcher-35 
Returned with URL: '/authenticate/google?state=3d6c8db1-1db0-4d68-80a3-371ea4d5d235&code=4/CmPPUaQ2SKhbfOx0FRRe1aA1fls1BNApK3CPqipmKQw'

2016-06-12 06:42:47,291 - [DEBUG] - from application in play-akka.actor.default-dispatcher-35 
{"access_token":"ya29.Ci__Ah7sLTMq9k1FNep13uy3yKMz4CN33OIPMXSM4XdiB9l4DyA4MSq-A2QA0btt8Q","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6IlNRbVluc3o1dGRFZFJUWnRTNGVjQUEiLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcxMDE2OCwiZXhwIjoxNDY1NzEzNzY4fQ.BRv7KcGacMj9VhvQ9z1lBITuz0XqErRpzDzQdv9_32u5lI_olJCbcC128hmfWiNKjJDLO8nn2RznnhB7OxFspGPjXcfF3S3dc0YR7Ocuzi9xigsxczUo7Ep8GCmfHQjK9RqQpJ5twpQVgU1zv1t58jjoGoc9EBiwSI-CqvB9LXMTGhbr40bU_gcbgjhLPToVbmyNoNlx9hkDCM6N0vrHG3_PVeCu2RphX2lurC1UlqY5YnV_SSvvPzAMB27D9pYsUXlXzg4iv18LxqQbO_yeU_G5yGeex1zcUN6zmcYq87tyrYFm-PNRxgcMW18vnH0ks1I6UAWnY3WVVQhpXE5mJw"}

2016-06-12 06:42:47,632 - [DEBUG] - from application in play-akka.actor.default-dispatcher-35 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 06:43:20,425 - [INFO] - from application in play-internal-execution-context-6 
Application started!

2016-06-12 06:43:21,106 - [DEBUG] - from application in play-internal-execution-context-6 
** Morphia datastore: ro

2016-06-12 06:43:21,107 - [INFO] - from application in play-internal-execution-context-6 
Connected to Database!

2016-06-12 06:43:21,236 - [WARN] - from application in play-internal-execution-context-6 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:43:21,239 - [INFO] - from play in play-internal-execution-context-6 
Application started (Dev)

2016-06-12 06:44:13,852 - [INFO] - from application in play-internal-execution-context-6 
Application started!

2016-06-12 06:44:14,511 - [DEBUG] - from application in play-internal-execution-context-6 
** Morphia datastore: ro

2016-06-12 06:44:14,512 - [INFO] - from application in play-internal-execution-context-6 
Connected to Database!

2016-06-12 06:44:14,643 - [WARN] - from application in play-internal-execution-context-6 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:44:14,648 - [INFO] - from play in play-internal-execution-context-6 
Application started (Dev)

2016-06-12 06:52:39,550 - [INFO] - from application in play-internal-execution-context-11 
Application started!

2016-06-12 06:52:40,202 - [DEBUG] - from application in play-internal-execution-context-11 
** Morphia datastore: ro

2016-06-12 06:52:40,202 - [INFO] - from application in play-internal-execution-context-11 
Connected to Database!

2016-06-12 06:52:40,332 - [WARN] - from application in play-internal-execution-context-11 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:52:40,334 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2016-06-12 06:52:50,884 - [DEBUG] - from application in play-akka.actor.default-dispatcher-61 
Returned with URL: '/authenticate/google'

2016-06-12 06:52:50,889 - [DEBUG] - from application in play-akka.actor.default-dispatcher-61 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=a7a6b5eb-c9c6-4427-a438-73424973cedf

2016-06-12 06:52:53,081 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
Returned with URL: '/authenticate/google?state=a7a6b5eb-c9c6-4427-a438-73424973cedf&code=4/GluctI91LxmddwJpiN8hUkwTuoLZjD_5FfsyFIbWwNI'

2016-06-12 06:52:53,381 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
{"access_token":"ya29.Ci__Ahrjlmr149cK4Gwqg9DzZ7pse_TUBWLnUqcgm07EvLxY7l0-AIKh5-6V0MUjOQ","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6Inl1d2htb1RJbXJRUnBON0tJajlmYnciLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcxMDc3NCwiZXhwIjoxNDY1NzE0Mzc0fQ.i6NMbsHdccjgYxqbf12TjjBdWbOrtdocQeQbIldnKLlbKM_q-e5_Ca70LBh108SoLyWCXh-3zPOT0JxGj4T-JLF8GWAiM9vbVuvP3six5YwUZmZCE8jISIDIABEL_n_8LMr1pfHdmVLk0jsVwh-I_lAMbgC8dkS79qC1cYQBleHxeHjKnZVQ0KideoFfC4h6AvX-lwOPmgDD38Fl_-bAFXy5CFRILpYKF0TqbApGuDjWG4uXrXP5vG7QMbvfuAmyreQVZ1md4kOgpWrqnPlzk_ktx5WWlg9aky_vIgQMIFDmXPUPN2SuFL68SpRCnXLJW5VpxD8Ts2HOPw-h4Jel8g"}

2016-06-12 06:52:53,694 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 06:54:38,931 - [ERROR] - from application in New I/O worker #8 


! @70ci16f9b - Internal server error, for (GET) [/logout] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value userList]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 06:54:48,897 - [ERROR] - from application in New I/O worker #8 


! @70ci1742i - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value userList]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 06:56:35,952 - [ERROR] - from application in New I/O worker #8 


! @70ci1d6c6 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: incompatible types: List<User> cannot be converted to List<Ro>]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 06:58:10,378 - [INFO] - from application in play-internal-execution-context-11 
Application started!

2016-06-12 06:58:11,049 - [DEBUG] - from application in play-internal-execution-context-11 
** Morphia datastore: ro

2016-06-12 06:58:11,049 - [INFO] - from application in play-internal-execution-context-11 
Connected to Database!

2016-06-12 06:58:11,180 - [WARN] - from application in play-internal-execution-context-11 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:58:11,181 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2016-06-12 06:58:30,955 - [DEBUG] - from application in play-akka.actor.default-dispatcher-75 
Returned with URL: '/authenticate/google'

2016-06-12 06:58:30,955 - [DEBUG] - from application in play-akka.actor.default-dispatcher-75 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=c42a77ae-4885-4ad5-92e9-941c2adec7b2

2016-06-12 06:58:33,346 - [DEBUG] - from application in play-akka.actor.default-dispatcher-75 
Returned with URL: '/authenticate/google?state=c42a77ae-4885-4ad5-92e9-941c2adec7b2&code=4/Z0LLPXeNBb2elpeObBQ5VBHW3EDNCn5Dq2kOViTMWBA'

2016-06-12 06:58:33,614 - [DEBUG] - from application in play-akka.actor.default-dispatcher-75 
{"access_token":"ya29.Ci__AoUjaCk2RTemllV-m9ePfFoBaAcM1yN1RUaHbOyZyrltxHvNCn3_8IC1YD4bsQ","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6Im16NGl5REZtcTFQQkV1MzNNaUQzWUEiLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcxMTExNSwiZXhwIjoxNDY1NzE0NzE1fQ.rE_X0m2WuZZu5mqbJ2FrHhc5dIxvadu7Vi7TrWY6TsDaDK0xk8NYD5zCwpbZIVyFFRRUfaLDBBmZ9G37yzOBmCJOGgVNRrFgcVIXKgjEB6_sgAEhhkbJMCS0pzGm_ng9Mokn4P2KsIbIw1ceOmH4GdA3Oe9HsGecow-oiE-nNahQS4EB1iCWt1FOg-ctxzec-RLQMHggpatQVCVTvvNSSQV8auIvZRAfQklgPFV_ikK0D3yj-IM5_XeI_r7eUwohium4nOUx8oLzbqTpm2KfbkvWHbw9YKZh6g0Kk3DMWChJpKm9rTjVpWFxeYVLKqIiMhPbJzNvrr7xrOXOZ0k0KQ"}

2016-06-12 06:58:33,912 - [DEBUG] - from application in play-akka.actor.default-dispatcher-75 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 06:59:47,093 - [INFO] - from application in play-internal-execution-context-11 
Application started!

2016-06-12 06:59:47,748 - [DEBUG] - from application in play-internal-execution-context-11 
** Morphia datastore: ro

2016-06-12 06:59:47,749 - [INFO] - from application in play-internal-execution-context-11 
Connected to Database!

2016-06-12 06:59:47,876 - [WARN] - from application in play-internal-execution-context-11 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 06:59:47,877 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2016-06-12 06:59:55,869 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
Returned with URL: '/authenticate/google'

2016-06-12 06:59:55,872 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=a2b0fbab-c808-48aa-9cb6-a4b9fa322f32

2016-06-12 06:59:57,906 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
Returned with URL: '/authenticate/google?state=a2b0fbab-c808-48aa-9cb6-a4b9fa322f32&code=4/kcWYHgUzFL5z6LPYGKksPEBOodEltcJSBYl2ljoYRS4'

2016-06-12 06:59:58,161 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
{"access_token":"ya29.Ci__Av_RnHVltB-d7fbpMFVGqrw2aae2rt3U0jnSj4tTwctu06_QlXZoO7-sOwG85Q","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6InVybGxGdjFzbkE1RGRDSng1Y3hVSkEiLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcxMTE5OSwiZXhwIjoxNDY1NzE0Nzk5fQ.G6nGQkVQqRTjfCAZlDg9QVFEiOMKMB8c_BOKJ_OILY3XMe72zQOPha8lbx-rKTtoLZH7o6a6cP-WXuXVAPAcazMlyC8WFc2dhiqQH7U-ZFmJqV9YGEV-CseSvm6Ydd70Yz90QLwLu71FkJLUX4lkHhwdBU72XoG-5TD0Nn1eEsg8a2HYK3BnS3Gdw5QUAekXm4AMjS_8UsHC_OH4pD6ozu4gbKptljTxlB65IE0Eew5Ej8cyHCVsERigCgwkJ-h8DGrPDfe8F90kFcmsnSZS7FPmbdOq9xY3MIF_CiUcohNCPlGMF3YXUo0oSe26z2tpYqfUxzEznIwhIfocaFZBnQ"}

2016-06-12 06:59:58,470 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 07:00:27,371 - [INFO] - from application in play-internal-execution-context-11 
Application started!

2016-06-12 07:00:28,140 - [DEBUG] - from application in play-internal-execution-context-11 
** Morphia datastore: ro

2016-06-12 07:00:28,141 - [INFO] - from application in play-internal-execution-context-11 
Connected to Database!

2016-06-12 07:00:28,273 - [WARN] - from application in play-internal-execution-context-11 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:00:28,274 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2016-06-12 07:00:43,735 - [INFO] - from application in play-internal-execution-context-11 
Application started!

2016-06-12 07:00:44,404 - [DEBUG] - from application in play-internal-execution-context-11 
** Morphia datastore: ro

2016-06-12 07:00:44,404 - [INFO] - from application in play-internal-execution-context-11 
Connected to Database!

2016-06-12 07:00:44,532 - [WARN] - from application in play-internal-execution-context-11 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:00:44,533 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2016-06-12 07:01:14,770 - [INFO] - from application in play-internal-execution-context-11 
Application started!

2016-06-12 07:01:15,441 - [DEBUG] - from application in play-internal-execution-context-11 
** Morphia datastore: ro

2016-06-12 07:01:15,441 - [INFO] - from application in play-internal-execution-context-11 
Connected to Database!

2016-06-12 07:01:15,571 - [WARN] - from application in play-internal-execution-context-11 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:01:15,572 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2016-06-12 07:01:56,845 - [INFO] - from application in play-internal-execution-context-11 
Application started!

2016-06-12 07:01:57,506 - [DEBUG] - from application in play-internal-execution-context-11 
** Morphia datastore: ro

2016-06-12 07:01:57,506 - [INFO] - from application in play-internal-execution-context-11 
Connected to Database!

2016-06-12 07:01:57,636 - [WARN] - from application in play-internal-execution-context-11 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:01:57,637 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2016-06-12 07:02:06,129 - [DEBUG] - from application in play-akka.actor.default-dispatcher-82 
Returned with URL: '/authenticate/google'

2016-06-12 07:02:06,135 - [DEBUG] - from application in play-akka.actor.default-dispatcher-82 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=85ba6df6-ce68-4305-9b48-98327e1af0f8

2016-06-12 07:02:06,138 - [DEBUG] - from application in play-akka.actor.default-dispatcher-96 
Returned with URL: '/authenticate/google'

2016-06-12 07:02:06,143 - [DEBUG] - from application in play-akka.actor.default-dispatcher-96 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=d4b13877-5d0c-45df-8cb2-d0b34a269b78

2016-06-12 07:02:08,374 - [DEBUG] - from application in play-akka.actor.default-dispatcher-98 
Returned with URL: '/authenticate/google?state=d4b13877-5d0c-45df-8cb2-d0b34a269b78&code=4/ijtp4bz8Xs2u2h4yK84yvsyLcEe75ijleaKW_c-PNWE'

2016-06-12 07:02:08,645 - [DEBUG] - from application in play-akka.actor.default-dispatcher-98 
{"access_token":"ya29.Ci__Aip6Ma61V0MkUJj3fQLI2LbmkP_EDnQoBL1JUurO4Gzu8nCPKZkN1edB64dZ2A","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6IlFhU2lzbUk2RWgzOWE3aHAwYzZUNlEiLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcxMTMzMCwiZXhwIjoxNDY1NzE0OTMwfQ.KxmA2yj9-GB6hcEHkUCxttENBwOtB8txOk0qPITsc_GiktcnorjxlVxNXGfyra9MkTe_Q1UrTmks-dofSpnqRn3YaMVfj1NWrB5Lasd9rjHNKvH31sdHLDTHUGyhlaaukeZP3AFQikhmt2GoHkJbNgAopZHBNO5EfKtHGUSRr7DbKVfQCmkhqrUB8dA54Nn_oY1MnpFX0omjrqqDIT1nYpuIuZmBdVFOYPCILjt5IT0H8Xkzlef7oi7HOYKLZnfa1eZipD-mxt1353wC8H7EZhatAhwqQqAjmpauezCm_VssGjt6tfNjPZYP8xjfzMO-sefYwibS0QemY2F384Vqbw"}

2016-06-12 07:02:08,966 - [DEBUG] - from application in play-akka.actor.default-dispatcher-98 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

2016-06-12 07:03:01,386 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:03:02,042 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:03:02,042 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:03:02,170 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:03:02,171 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:03:35,847 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:03:36,496 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:03:36,496 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:03:36,624 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:03:36,625 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:11:04,381 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:11:05,045 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:11:05,045 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:11:05,175 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:11:05,177 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:12:03,843 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:12:04,500 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:12:04,501 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:12:04,630 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:12:04,634 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:14:37,496 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:14:38,150 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:14:38,150 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:14:38,277 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:14:38,278 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:16:09,840 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:16:10,491 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:16:10,491 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:16:10,619 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:16:10,620 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:16:29,684 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:16:30,351 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:16:30,351 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:16:30,478 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:16:30,480 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:17:11,235 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:17:11,952 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:17:11,952 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:17:12,080 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:17:12,081 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:19:24,257 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:19:24,910 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:19:24,910 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:19:25,039 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:19:25,039 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:20:17,678 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:20:18,327 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:20:18,327 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:20:18,458 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:20:18,459 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:24:53,001 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 07:24:53,652 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 07:24:53,653 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 07:24:53,784 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 07:24:53,787 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 07:50:25,697 - [ERROR] - from application in New I/O worker #6 


! @70ci8f055 - Internal server error, for (GET) [/user] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value url]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 07:59:10,871 - [ERROR] - from application in New I/O worker #7 


! @70ci9in22 - Internal server error, for (GET) [/user] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value url]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:03:56,973 - [ERROR] - from application in New I/O worker #7 


! @70cia9480 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value url]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:05:16,779 - [ERROR] - from application in New I/O worker #7 


! @70ciadi9g - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: type File]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:05:39,953 - [ERROR] - from application in New I/O worker #7 


! @70ciaf0gm - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : String
 required: java.io.File]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:07:10,300 - [ERROR] - from application in New I/O worker #7 


! @70ciak47k - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: type File]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:12:58,527 - [ERROR] - from application in New I/O worker #8 


! @70cibdpb4 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: type File]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:26:08,970 - [ERROR] - from application in New I/O worker #1 


! @70cid6oi9 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: type File]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:26:22,580 - [ERROR] - from application in New I/O worker #1 


! @70cid7im5 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value url]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:27:12,113 - [ERROR] - from application in New I/O worker #1 


! @70cidae2p - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value url]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:28:51,561 - [ERROR] - from application in New I/O worker #1 


! @70cidg54d - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value url]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:29:24,967 - [ERROR] - from application in New I/O worker #1 


! @70cidi2h4 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:38:53,535 - [ERROR] - from application in New I/O worker #2 


! @70cieobi8 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: cannot find symbol]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.1.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]

2016-06-12 08:41:02,229 - [INFO] - from application in play-internal-execution-context-17 
Application started!

2016-06-12 08:41:02,885 - [DEBUG] - from application in play-internal-execution-context-17 
** Morphia datastore: ro

2016-06-12 08:41:02,886 - [INFO] - from application in play-internal-execution-context-17 
Connected to Database!

2016-06-12 08:41:03,019 - [WARN] - from application in play-internal-execution-context-17 
A user service was already registered - replacing the old one (service.MyUserServicePlugin) with the new one (service.MyUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2016-06-12 08:41:03,021 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2016-06-12 08:41:14,541 - [DEBUG] - from application in play-akka.actor.default-dispatcher-182 
Path where we are coming from (/user) is different than the login URL (/login)

2016-06-12 08:41:22,777 - [DEBUG] - from application in play-akka.actor.default-dispatcher-185 
Returned with URL: '/authenticate/google'

2016-06-12 08:41:22,879 - [DEBUG] - from application in play-akka.actor.default-dispatcher-185 
generated redirect URL for dialog: https://accounts.google.com/o/oauth2/auth?client_id=912436160264-ev191lmaculrtniv0qkq4uregdptcuvf.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&state=85f69f98-f38b-4ce7-a18f-98285e981b47

2016-06-12 08:41:27,508 - [DEBUG] - from application in play-akka.actor.default-dispatcher-184 
Returned with URL: '/authenticate/google?state=85f69f98-f38b-4ce7-a18f-98285e981b47&code=4/z3ZdXCS1avuaLtcoVKcS1cDedTLdmq_4B78x-YSaFuM'

2016-06-12 08:41:29,489 - [DEBUG] - from application in play-akka.actor.default-dispatcher-184 
{"access_token":"ya29.Ci__AvDzcb6_dFKHcEiE4W7RgDYuwBBWEB3r55byPYKzOotaDJ53l1B7pGmunBR3KQ","token_type":"Bearer","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVjMzEwYWY5Y2E1MjNkOTFkZjQ0ZjU1ZTgyYjI3YjcwMGI4N2U2ZWMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6ImRJMnN2dlM4S0RSdmZrR2k0SDNIdmciLCJhdWQiOiI5MTI0MzYxNjAyNjQtZXYxOTFsbWFjdWxydG5pdjBxa3E0dXJlZ2RwdGN1dmYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMwNDI1NjA2MTUwMDQyMTgyNjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiOTEyNDM2MTYwMjY0LWV2MTkxbG1hY3VscnRuaXYwcWtxNHVyZWdkcHRjdXZmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJtZWNoYW5pY2FsLm1hZ2dvdC4wQGdtYWlsLmNvbSIsImlhdCI6MTQ2NTcxNzI5MCwiZXhwIjoxNDY1NzIwODkwfQ.kCm_EuBVS1DYaWsoksURCU1eWkx9_jPwH3WrtbYOcp-SNzjaZHAmFbgkDzzva0wpKxYvJnzDSiUqbDlffgBW6Vh7I9vINVAm_OqZQUtY9IqwK0o2pEV1ehWIZkPeeztahctQfnYhU8yDq417g_RwzsAiBAZ-1jsqkDg5_aZ2f58s5GzcT5lxJJqQeLYy1th0aU6Gd1oaRIWVWL9KbuvsjBC5oMYS0kJdvhfViJcJoRv6QBZfiiTqA0e7nnvZIlUE3_PJRAs9UxT25zCrrCpZ9A39zocuY7fOkEUdPo1mWme20vLp19ZvYH1JovlkZknzJDTi80lLjQ6J3u2KG2lZ5Q"}

2016-06-12 08:41:29,867 - [DEBUG] - from application in play-akka.actor.default-dispatcher-184 
{"id":"113042560615004218262","email":"mechanical.maggot.0@gmail.com","verified_email":true,"name":"André Humberto","given_name":"André","family_name":"Humberto","link":"https://plus.google.com/113042560615004218262","picture":"https://lh5.googleusercontent.com/-Yf5rYd2OtDE/AAAAAAAAAAI/AAAAAAAAAEU/0jwWCODtavw/photo.jpg","gender":"male","locale":"pt-PT"}

